// Rasterize the canonical Tangle knot from @tangle-network/brand into the PNG
// that email headers embed. Email clients do not render SVG, so the kit ships
// this one bitmap: 3x the 28px header size, transparent background.
//
//   node scripts/email-mark.mjs
import { writeFileSync } from 'node:fs'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { TangleKnot } from '@tangle-network/brand'
import { chromium } from 'playwright'

const SIZE = 28
const SCALE = 3

const svg = renderToStaticMarkup(createElement(TangleKnot, { size: SIZE }))
const browser = await chromium.launch()
try {
  const page = await browser.newPage({ viewport: { width: SIZE, height: SIZE }, deviceScaleFactor: SCALE })
  await page.setContent(`<!doctype html><body style="margin:0;background:transparent">${svg}</body>`)
  const png = await page.locator('svg').screenshot({ omitBackground: true })
  const source = [
    '// GENERATED by scripts/email-mark.mjs from @tangle-network/brand TangleKnot; do not edit.',
    `/** The Tangle knot as a ${SIZE * SCALE}px transparent PNG (base64), shown at ${SIZE}px in email headers. */`,
    `export const TANGLE_MARK_PNG_BASE64 =\n  '${png.toString('base64')}'`,
    '',
  ].join('\n')
  writeFileSync(new URL('../src/email/mark.generated.ts', import.meta.url), source)
  console.log(`wrote src/email/mark.generated.ts (${png.length} bytes)`)
} finally {
  await browser.close()
}
