#!/usr/bin/env node
/**
 * gen-codemap — deterministic code-map + API reference for @tangle-network/agent-app.
 *
 * The published surface is the `entry` map in `tsup.config.ts` (subpath →
 * `src/<x>/index.ts`). The hand-maintained tables in README.md / AGENTS.md drift;
 * this regenerates the reference from source so CI can gate on it.
 *
 * It loads each entry through the TypeScript compiler API and enumerates the
 * PUBLIC exports with `checker.getExportsOfModule` — which follows the
 * `export * from './x'` re-export chains correctly — so it never has to run the
 * `pnpm build` d.ts step (that OOMs). For each export it records the kind, a
 * one-line signature, and the first sentence of the leading doc comment. It also
 * computes, per subpath, which OTHER agent-app subpaths it imports (the
 * intra-package dependency edge).
 *
 *   node scripts/gen-codemap.mjs           # write docs/CODEMAP.md + docs/api/*.md
 *   node scripts/gen-codemap.mjs --check   # fail (exit 1) if the committed docs are stale
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import ts from 'typescript'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'src')
const HEADER = '<!-- GENERATED by scripts/gen-codemap.mjs — DO NOT EDIT BY HAND. Run `pnpm docs:gen`. -->'

/** Parse the `entry` map out of tsup.config.ts (handles object and array forms). */
function loadEntries() {
  const configPath = join(ROOT, 'tsup.config.ts')
  const sf = ts.createSourceFile(configPath, readFileSync(configPath, 'utf8'), ts.ScriptTarget.Latest, true)
  let init
  const visit = (node) => {
    if (
      ts.isPropertyAssignment(node) &&
      (ts.isIdentifier(node.name) || ts.isStringLiteral(node.name)) &&
      node.name.text === 'entry'
    ) {
      init = node.initializer
    }
    ts.forEachChild(node, visit)
  }
  visit(sf)
  if (!init) throw new Error('tsup.config.ts: could not find an `entry` property')

  const files = []
  if (ts.isObjectLiteralExpression(init)) {
    for (const prop of init.properties) {
      if (ts.isPropertyAssignment(prop) && ts.isStringLiteral(prop.initializer)) files.push(prop.initializer.text)
    }
  } else if (ts.isArrayLiteralExpression(init)) {
    for (const el of init.elements) if (ts.isStringLiteral(el)) files.push(el.text)
  } else {
    throw new Error('tsup.config.ts: `entry` is neither an object nor an array literal')
  }

  return files.map((file) => {
    // `src/chat-routes/index.ts` → key `chat-routes/index`; drop a trailing /index.
    const key = file.replace(/^src\//, '').replace(/\.[tj]sx?$/, '')
    const id = key === 'index' ? '.' : key.replace(/\/index$/, '')
    const exportPath = id === '.' ? '.' : `./${id}`
    const apiName = (id === '.' ? 'index' : id).replace(/\//g, '-')
    const topDir = file.replace(/^src\//, '').split('/')[0]
    return { id, exportPath, file, apiName, topDir, absFile: join(ROOT, file), srcDir: dirname(join(ROOT, file)) }
  })
}

/** Build one TS program over every entry file, reusing the repo's tsconfig options. */
function createProgram(entries) {
  const cfg = ts.readConfigFile(join(ROOT, 'tsconfig.json'), ts.sys.readFile)
  const parsed = ts.parseJsonConfigFileContent(cfg.config ?? {}, ts.sys, ROOT)
  const options = { ...parsed.options, noEmit: true, skipLibCheck: true }
  return ts.createProgram(entries.map((e) => e.absFile), options)
}

const truncate = (s, n) => (s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s)

/** First sentence of a doc-comment block, whitespace-collapsed. */
function firstSentence(text) {
  const flat = text.replace(/\s+/g, ' ').trim()
  if (!flat) return ''
  const m = flat.match(/^(.*?[.!?])(\s|$)/)
  return truncate(m ? m[1] : flat, 200)
}

/** Kind + one-line signature + doc summary for one exported symbol. */
function describe(checker, exported) {
  let sym = exported
  if (sym.flags & ts.SymbolFlags.Alias) {
    try {
      sym = checker.getAliasedSymbol(sym)
    } catch {
      sym = exported
    }
  }
  const name = exported.getName()
  const decl = sym.valueDeclaration ?? sym.declarations?.[0]
  const f = sym.flags
  let kind
  let signature
  if (f & ts.SymbolFlags.Class) {
    kind = 'class'
    signature = `class ${name}`
  } else if (f & ts.SymbolFlags.Interface) {
    kind = 'interface'
    signature = `interface ${name}`
  } else if (f & ts.SymbolFlags.TypeAlias) {
    kind = 'type'
    signature = `type ${name}`
  } else if (f & ts.SymbolFlags.Enum || f & ts.SymbolFlags.EnumMember) {
    kind = 'enum'
    signature = `enum ${name}`
  } else if (f & (ts.SymbolFlags.Module | ts.SymbolFlags.ValueModule | ts.SymbolFlags.NamespaceModule)) {
    kind = 'namespace'
    signature = `namespace ${name}`
  } else if (decl) {
    const type = checker.getTypeOfSymbolAtLocation(sym, decl)
    const callable = type.getCallSignatures().length > 0
    kind = f & ts.SymbolFlags.Function || callable ? 'function' : 'const'
    signature = truncate(checker.typeToString(type).replace(/\s+/g, ' '), 120)
  } else {
    kind = 'value'
    signature = name
  }

  let doc = ts.displayPartsToString(exported.getDocumentationComment(checker)).trim()
  if (!doc && sym !== exported) doc = ts.displayPartsToString(sym.getDocumentationComment(checker)).trim()
  return { name, kind, signature, doc: firstSentence(doc) }
}

/** Public exports of one entry module, sorted by name, skipping synthetic __names. */
function exportsOf(program, checker, entry) {
  const sf = program.getSourceFile(entry.absFile)
  if (!sf) return { error: `no source file for ${entry.file}` }
  const moduleSym = checker.getSymbolAtLocation(sf)
  if (!moduleSym) return { error: `no module symbol for ${entry.file} (empty or non-module?)` }
  const exports = checker
    .getExportsOfModule(moduleSym)
    .filter((s) => !s.getName().startsWith('__'))
    .map((s) => describe(checker, s))
    .sort((a, b) => a.name.localeCompare(b.name))
  return { exports }
}

const walk = (dir) =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = join(dir, e.name)
    if (e.isDirectory()) return walk(p)
    return /\.(ts|tsx)$/.test(e.name) ? [p] : []
  })

/** Sibling agent-app subpaths this entry imports (via relative import/export specifiers). */
function siblingDeps(entry, topDirs) {
  const deps = new Set()
  for (const file of walk(entry.srcDir)) {
    const text = readFileSync(file, 'utf8')
    for (const m of text.matchAll(/(?:from|import)\s*\(?\s*['"](\.[^'"]*)['"]/g)) {
      const abs = resolve(dirname(file), m[1])
      if (!abs.startsWith(SRC + '/')) continue
      const seg = relative(SRC, abs).split('/')[0]
      if (seg && seg !== entry.topDir && topDirs.has(seg)) deps.add(seg)
    }
  }
  return [...deps].sort()
}

function build() {
  const entries = loadEntries().sort((a, b) => a.exportPath.localeCompare(b.exportPath))
  const topDirs = new Set(entries.map((e) => e.topDir))
  const program = createProgram(entries)
  const checker = program.getTypeChecker()

  const rows = entries.map((entry) => {
    const { exports = [], error } = exportsOf(program, checker, entry)
    return { entry, exports, error, deps: siblingDeps(entry, topDirs) }
  })

  const files = new Map()
  files.set('docs/CODEMAP.md', renderCodemap(rows))
  for (const row of rows) files.set(`docs/api/${row.entry.apiName}.md`, renderApiPage(row))
  return { files, rows }
}

function renderCodemap(rows) {
  const lines = [HEADER, '', '# agent-app code map', '']
  lines.push(
    `_${rows.length} published subpaths — source of truth: \`tsup.config.ts\` \`entry\`. Regenerate with \`pnpm docs:gen\`._`,
    '',
    '| Subpath | Exports | Depends on (siblings) |',
    '|---|---|---|',
  )
  for (const { entry, exports, error, deps } of rows) {
    const link = `[\`${entry.exportPath}\`](api/${entry.apiName}.md)`
    const count = error ? '—' : String(exports.length)
    const dep = deps.length ? deps.map((d) => `\`${d}\``).join(', ') : '—'
    lines.push(`| ${link} | ${count} | ${dep} |`)
  }
  lines.push('', '---', '')
  for (const { entry, exports, error, deps } of rows) {
    lines.push(`## \`${entry.exportPath}\``, '')
    lines.push(`Source: \`${entry.file}\` · ${error ? 'introspection failed' : `${exports.length} exports`}`, '')
    if (deps.length) lines.push(`Depends on: ${deps.map((d) => `\`${d}\``).join(', ')}`, '')
    if (error) {
      lines.push(`> Could not introspect: ${error}`, '')
    } else if (exports.length) {
      lines.push(exports.map((e) => `\`${e.name}\``).join(', '), '')
      lines.push(`[Full API →](api/${entry.apiName}.md)`, '')
    } else {
      lines.push('_No public exports._', '')
    }
  }
  return `${lines.join('\n').trimEnd()}\n`
}

function renderApiPage({ entry, exports, error }) {
  const lines = [HEADER, '', `# \`${entry.exportPath}\``, '']
  lines.push(`Source: \`${entry.file}\``, '')
  if (error) {
    lines.push(`> Could not introspect this subpath: ${error}`, '')
    return `${lines.join('\n').trimEnd()}\n`
  }
  lines.push(`${exports.length} export${exports.length === 1 ? '' : 's'}.`, '')
  for (const e of exports) {
    lines.push(`### \`${e.name}\``, '')
    lines.push(`\`${e.kind}\`${e.doc ? ` — ${e.doc}` : ''}`, '')
    lines.push('```ts', e.signature, '```', '')
  }
  return `${lines.join('\n').trimEnd()}\n`
}

function writeAll() {
  const { files } = build()
  const apiDir = join(ROOT, 'docs', 'api')
  if (existsSync(apiDir)) rmSync(apiDir, { recursive: true, force: true })
  mkdirSync(apiDir, { recursive: true })
  for (const [rel, content] of files) {
    const abs = join(ROOT, rel)
    mkdirSync(dirname(abs), { recursive: true })
    writeFileSync(abs, content)
  }
  return files
}

/** Compare freshly-generated output against what is committed on disk. */
function check() {
  const { files } = build()
  const stale = []
  const missing = []
  for (const [rel, content] of files) {
    const abs = join(ROOT, rel)
    if (!existsSync(abs)) missing.push(rel)
    else if (readFileSync(abs, 'utf8') !== content) stale.push(rel)
  }
  const apiDir = join(ROOT, 'docs', 'api')
  const orphan = existsSync(apiDir)
    ? readdirSync(apiDir)
        .filter((f) => f.endsWith('.md'))
        .map((f) => `docs/api/${f}`)
        .filter((rel) => !files.has(rel))
    : []
  return { ok: stale.length + missing.length + orphan.length === 0, stale, missing, orphan }
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href
if (isMain) {
  if (process.argv.includes('--check')) {
    const { ok, stale, missing, orphan } = check()
    if (ok) {
      console.log('codemap: docs are fresh')
      process.exit(0)
    }
    console.error('codemap: docs are STALE — run `pnpm docs:gen` and commit the result.')
    for (const f of missing) console.error(`  missing:  ${f}`)
    for (const f of stale) console.error(`  changed:  ${f}`)
    for (const f of orphan) console.error(`  orphaned: ${f}`)
    process.exit(1)
  }
  const files = writeAll()
  console.log(`codemap: wrote ${files.size} files (docs/CODEMAP.md + ${files.size - 1} API pages)`)
}
